services:
  api:
    restart: always
    build:
      context: ./apserver
      target: developer
    container_name: "api_langchain"
    # command: ["python", "main.py"]
    environment:
      MYSQL_DATABASE: langchainproject
      MYSQL_USER: pythonMySql1
      MYSQL_PASSWORD: pythonMySql1
    volumes:
      - ./apserver:/app
    tty: true
    ports:
      - 8000:8000
  db:
    image: mysql:8.0.37-oracle
    container_name: "db_langchain"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: langchainproject
      MYSQL_USER: pythonMySql1
      MYSQL_PASSWORD: pythonMySql1
      TZ: 'Asia/Tokyo'
    command: mysqld
    # volumes:
    #   - ./dbserver/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
