services:
  api:
    restart: always
    build:
      context: ./apserver
      target: developer
    container_name: "api_langchain"
    volumes:
      - ./apserver:/app
    tty: true
  db:
    image: chromadb/chroma:latest
    container_name: "db_langchain"
    restart: always
    ports:
      - 8000:8000
    volumes:
        - ./dbserver/data:/chroma/.chroma/index
